name: Jupyter Notebook Javascript Tests
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.5', '3.6', '3.7', '3.8' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - uses: actions/setup-node@v1
      with:
        node-version: '6.9.2'
    - name: Install development environment
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel nose coverage codecov
        npm install
    - name: Install Javascript dependencies.
      run: |
        npm install -g casperjs@1.1.3 phantomjs-prebuilt@2.1.7
    - name: Install the Python dependencies
      run: |
        pip install -e .[test]
        pip freeze
        wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb
    - name: Run the tests
      run: |
        python -m notebook.jstest js/services