name: Jupyter Notebook Selenium Tests
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.5', '3.6', '3.7', '3.8' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Install development environment
      run: |
        pip install --upgrade pip
        pip install --upgrade setuptools wheel nose coverage codecov
        nvm install 6.9.2
        nvm use 6.9.2
        node --version
        npm --version
        npm upgrade -g npm
        npm install
    - name: Install Selenium dependencies.
      run: |
        pip install --upgrade selenium pytest
        # Install Webdriver backend for Firefox:
        wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
        export PATH=$PATH:$PWD/geckodriver
    - name: Install the Python dependencies
      run: |
        pip install -e .[test]
        pip freeze
        wget https://github.com/jgm/pandoc/releases/download/1.19.1/pandoc-1.19.1-1-amd64.deb && sudo dpkg -i pandoc-1.19.1-1-amd64.deb
    - name: Run the tests
      run: |
        py.test -sv notebook/tests/selenium